spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mappeo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true